### DISCUSSION TITLE
Seplos 2.0 Yaml File

### DISCUSSION THREAD

**Discussion by ebagnoli** [syssi/esphome-seplos-bms#118] [Q&A]
Hi all, i'm getting in trouble having a single Seplos 2.0 connected to Esp32 via RS485 to TTL. Does somebody of you have the Seplos 2.0 and can help me, sharing the Yaml file to flash in the ESP 32, or telling me if the baud rate is 9600 or 19200.
Any help is really appreciated.

**Comment by rvdgaag** [comment]
This yaml reads both my slave seplos bms's, for the Master a have a different ESP32 and setup:

[esphome-web-282894.yaml.zip](https://github.com/user-attachments/files/18211550/esphome-web-282894.yaml.zip)

**Reply by ebagnoli** [reply]
> This yaml reads both my slave seplos bms's, for the Master a have a different ESP32 and setup:
> 
> [esphome-web-282894.yaml.zip](https://github.com/user-attachments/files/18211550/esphome-web-282894.yaml.zip)

hi rvdaag, cann you send me the master esp32 yaml file? thanks

**Comment by ebagnoli** [comment]
Tank you so much for your reply. Can you also tell me at which pin of your esp32 you have soldered the tx and Rx  wires coming from your TTL converter and gf you power it at 3 or 5 volts. Somewhere there is a problem.

**Comment by rvdgaag** [comment]
The pins ate mentioned in de yaml, gpio

I have 5v in to the esp32 and the ttl board in the 3v of the esp32
________________________________
Van: ebagnoli ***@***.***>
Verzonden: Friday, December 20, 2024 6:38:09 PM
Aan: syssi/esphome-seplos-bms ***@***.***>
CC: rvdgaag ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [syssi/esphome-seplos-bms] Seplos 2.0 Yaml File (Discussion #118)


Tank you so much for your reply. Can you also tell me at which pin of your esp32 you have soldered the tx and Rx wires coming from your TTL converter and gf you power it at 3 or 5 volts. Somewhere there is a problem.

**Reply by ebagnoli** [reply]
Thanks a lot, but this means that you solder  tx_pin: 17 and   rx_pin: 16. I put this question because in my esp32  for the moment  tx_pin: GPIO3  rx_pin: GPIO1

**Reply by tugsi** [reply]
I didn´t open the YAML, but normally you can define the GPIOs you prefer to use, if rvdgaag use 17/18 then you can change there to your 3/1 and it should be work with your soldering

**Reply by ebagnoli** [reply]
The problem is that I have tested everythinh and I cannot read any value in Homeassistant.
A friend of mine who has a similar configuration tells me that without the seploss connected on the ttl board only the TX led has to blink. Can you confirm me this? I have bought a usb rs485. So I'm sure about the 2 wires and about the baudrate that is 19200. I can read values by serial but not via ESP32. Where is the problem?

**Reply by syssi** [reply]
This is correct. This project/implementation sends requests periodically which gets indicated by the TX LED. If you receive some response the RX LED should blink too. If the RX LED blinks periodically your wiring isn't correct. If no LED blinks the `uart` isn't assigned to the correct GPIOs or your wiring is totally wrong (f.e. the RS485 converter isn't powered).

**Comment by ebagnoli** [comment]
Everything is correct, but it doesn't work. The last option is to invert A and B on the TTL converter hopinh that there is a mistake on the printing of this label. I repeat on USB to 485 everithing is fine with White Brown on A and Brown on B, 19200. I have a seploss 2.0

**Comment by ebagnoli** [comment]
![Immagine WhatsApp 2024-12-21 ore 12 31 38_776f664b](https://github.com/user-attachments/assets/8162efa2-0b8d-426c-b718-8b727140e3d4)

**Comment by ebagnoli** [comment]
and this is my wiring with TX and RX going on 17 an 16

![Immagine WhatsApp 2024-12-21 ore 21 21 08_14a31a11](https://github.com/user-attachments/assets/65a5b84d-53a8-416c-a3eb-e2014edb13ba)

**Comment by ebagnoli** [comment]
And this is the config file 

uart:
  id: uart_0
  # Please set the default baudrate of your Seplos BMS model here. It's sometimes 19200 baud instead of 9600.
  baud_rate: 19200
  tx_pin: 17
  rx_pin: 16
  # The increased RX buffer size is important because
  # the full BMS response must fit into the buffer
  rx_buffer_size: 384

**Comment by ebagnoli** [comment]
```
api:
  encryption:
    key: "U8Ekj3cyBuf4fnTOK0UXf4YMXOXQtREOcXcCCGQDSVM="

ota:
  - platform: esphome
    password: "84113e8889ecccf3df7d3e3f0d0ed4a5"

wifi:
  ssid: WLANCasale
  password: lisaolga

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Seplos2 Fallback Hotspot"
    password: "wbzj5RUOti25"

esphome:
  name: esphome-web-282894
  friendly_name: ESPHome Seplos Slaves BMS

esp32:
  board: esp32dev
  framework:
    type: arduino



substitutions:
  name: seplos-bms
  device_description: "Monitor a Seplos BMS via RS485"
  battery_bank1: "${name} bank 1"
  battery_bank2: "${name} bank 2"
  external_components_source: github://syssi/esphome-seplos-bms@main



external_components:
  - source: ${external_components_source}
    refresh: 0s


web_server:
  port: 80

# Enable logging
logger:

# If you use Home Assistant please remove this `mqtt` section and uncomment the `api` component!
# The native API has many advantages over MQTT: https://esphome.io/components/api.html#advantages-over-mqtt
#mqtt:
 # broker: "192.168.2.101"
 # username: "energie"
 # password: "chicco3848" 
 # id: mqtt_bms



uart:
  id: uart_0
  # Please set the default baudrate of your Seplos BMS model here. It's sometimes 19200 baud instead of 9600.
  baud_rate: 19200
  tx_pin: 17
  rx_pin: 16
  # The increased RX buffer size is important because
  # the full BMS response must fit into the buffer
  rx_buffer_size: 384
  

seplos_modbus:
  id: modbus0
  uart_id: uart_0
  rx_timeout: 50ms
  #flow_control_pin: 4 #for use when you use a rs485 board without auto flow control. Like the rs485 max board.

seplos_bms:
  - id: battery_bank1
    # Dip switch configuration of the first pack / address 0x01
    #  8    7    6    5    4    3    2   1
    # off, off, off, off, off, off, off, on
    address: 0x00
    # Known protocol versions: 0x20 (Seplos), 0x26 (Boqiang)
    protocol_version: 0x20
    #override_pack: 1
    seplos_modbus_id: modbus0
    update_interval: 10s
  - id: battery_bank2
    # Dip switch configuration of the second pack / address 0x02
    #  8    7    6    5    4    3   2    1
    # off, off, off, off, off, off, on, off
    address: 0x02
    # Known protocol versions: 0x20 (Seplos), 0x26 (Boqiang)
    protocol_version: 0x20
    #override_pack: 2
    seplos_modbus_id: modbus0
    update_interval: 3s
    

sensor:
  #- platform: seplos_bms
  #  seplos_bms_id: battery_bank1
  #  min_cell_voltage:
  #    name: "${battery_bank1} min cell voltage"
  #  max_cell_voltage:
  #    name: "${battery_bank1} max cell voltage"
  #  delta_cell_voltage:
  #    name: "${battery_bank1} delta cell voltage"
  #  average_cell_voltage:
  #    name: "${battery_bank1} average cell voltage"
  #  total_voltage:
  #    name: "${battery_bank1} total voltage"
  #  current:
  #    name: "${battery_bank1} current"
  #  power:
  #    name: "${battery_bank1} power"
  #  state_of_charge:
  #    name: "${battery_bank1} state of charge"

  - platform: seplos_bms
    seplos_bms_id: battery_bank1
    min_cell_voltage:
      name: "${battery_bank1} min cell voltage"
    max_cell_voltage:
      name: "${battery_bank1} max cell voltage"
    min_voltage_cell:
      name: "${battery_bank1} min voltage cell"
    max_voltage_cell:
      name: "${battery_bank1} max voltage cell"
    delta_cell_voltage:
      name: "${battery_bank1} delta cell voltage"
    average_cell_voltage:
      name: "${battery_bank1} average cell voltage"
    cell_voltage_1:
      name: "${battery_bank1} cell voltage 1"
    cell_voltage_2:
      name: "${battery_bank1} cell voltage 2"
    cell_voltage_3:
      name: "${battery_bank1} cell voltage 3"
    cell_voltage_4:
      name: "${battery_bank1} cell voltage 4"
    cell_voltage_5:
      name: "${battery_bank1} cell voltage 5"
    cell_voltage_6:
      name: "${battery_bank1} cell voltage 6"
    cell_voltage_7:
      name: "${battery_bank1} cell voltage 7"
    cell_voltage_8:
      name: "${battery_bank1} cell voltage 8"
    cell_voltage_9:
      name: "${battery_bank1} cell voltage 9"
    cell_voltage_10:
      name: "${battery_bank1} cell voltage 10"
    cell_voltage_11:
      name: "${battery_bank1} cell voltage 11"
    cell_voltage_12:
      name: "${battery_bank1} cell voltage 12"
    cell_voltage_13:
      name: "${battery_bank1} cell voltage 13"
    cell_voltage_14:
      name: "${battery_bank1} cell voltage 14"
    cell_voltage_15:
      name: "${battery_bank1} cell voltage 15"
    cell_voltage_16:
      name: "${battery_bank1} cell voltage 16"
    temperature_1:
      name: "${battery_bank1} temperature 1"
    temperature_2:
      name: "${battery_bank1} temperature 2"
    temperature_3:
      name: "${battery_bank1} temperature 3"
    temperature_4:
      name: "${battery_bank1} temperature 4"
    temperature_5:
      name: "${battery_bank1} environment temperature"
    temperature_6:
      name: "${battery_bank1} mosfet temperature"
    total_voltage:
      name: "${battery_bank1} total voltage"
    current:
      name: "${battery_bank1} current"
    power:
      name: "${battery_bank1} power"
    charging_power:
      name: "${battery_bank1} charging power"
    discharging_power:
      name: "${battery_bank1} discharging power"
    residual_capacity:
      name: "${battery_bank1} residual capacity"
    battery_capacity:
      name: "${battery_bank1} battery capacity"
    rated_capacity:
      name: "${battery_bank1} rated capacity"
    state_of_charge:
      name: "${battery_bank1} state of charge"
    charging_cycles:
      name: "${battery_bank1} charging cycles"
    state_of_health:
      name: "${battery_bank1} state of health"
    port_voltage:
      name: "${battery_bank1} port voltage"




  - platform: seplos_bms
    seplos_bms_id: battery_bank2
    min_cell_voltage:
      name: "${battery_bank2} min cell voltage"
    max_cell_voltage:
      name: "${battery_bank2} max cell voltage"
    min_voltage_cell:
      name: "${battery_bank2} min voltage cell"
    max_voltage_cell:
      name: "${battery_bank2} max voltage cell"
    delta_cell_voltage:
      name: "${battery_bank2} delta cell voltage"
    average_cell_voltage:
      name: "${battery_bank2} average cell voltage"
    cell_voltage_1:
      name: "${battery_bank2} cell voltage 1"
    cell_voltage_2:
      name: "${battery_bank2} cell voltage 2"
    cell_voltage_3:
      name: "${battery_bank2} cell voltage 3"
    cell_voltage_4:
      name: "${battery_bank2} cell voltage 4"
    cell_voltage_5:
      name: "${battery_bank2} cell voltage 5"
    cell_voltage_6:
      name: "${battery_bank2} cell voltage 6"
    cell_voltage_7:
      name: "${battery_bank2} cell voltage 7"
    cell_voltage_8:
      name: "${battery_bank2} cell voltage 8"
    cell_voltage_9:
      name: "${battery_bank2} cell voltage 9"
    cell_voltage_10:
      name: "${battery_bank2} cell voltage 10"
    cell_voltage_11:
      name: "${battery_bank2} cell voltage 11"
    cell_voltage_12:
      name: "${battery_bank2} cell voltage 12"
    cell_voltage_13:
      name: "${battery_bank2} cell voltage 13"
    cell_voltage_14:
      name: "${battery_bank2} cell voltage 14"
    cell_voltage_15:
      name: "${battery_bank2} cell voltage 15"
    cell_voltage_16:
      name: "${battery_bank2} cell voltage 16"
    temperature_1:
      name: "${battery_bank2} temperature 1"
    temperature_2:
      name: "${battery_bank2} temperature 2"
    temperature_3:
      name: "${battery_bank2} temperature 3"
    temperature_4:
      name: "${battery_bank2} temperature 4"
    temperature_5:
      name: "${battery_bank2} environment temperature"
    temperature_6:
      name: "${battery_bank2} mosfet temperature"
    total_voltage:
      name: "${battery_bank2} total voltage"
    current:
      name: "${battery_bank2} current"
    power:
      name: "${battery_bank2} power"
    charging_power:
      name: "${battery_bank2} charging power"
    discharging_power:
      name: "${battery_bank2} discharging power"
    residual_capacity:
      name: "${battery_bank2} residual capacity"
    battery_capacity:
      name: "${battery_bank2} battery capacity"
    rated_capacity:
      name: "${battery_bank2} rated capacity"
    state_of_charge:
      name: "${battery_bank2} state of charge"
    charging_cycles:
      name: "${battery_bank2} charging cycles"
    state_of_health:
      name: "${battery_bank2} state of health"
    port_voltage:
      name: "${battery_bank2} port voltage"
```

**Comment by ebagnoli** [comment]
And this is my config file: Just a question, are we sure that the file Yaml is ok for a Seplos 2.0 with only one battery in master?

**Comment by ebagnoli** [comment]
Ok, tanks to all of you that helped me. After 10 days of testing I have a yaml file that works with a seplos 2.0 in master

**Comment by ebagnoli** [comment]
```
# Enable Home Assistant API

substitutions:
  name: seplos-bms
  device_description: "Monitor a Seplos BMS via RS485"
  external_components_source: github://syssi/esphome-seplos-bms@main
  tx_pin: GPIO17
  rx_pin: GPIO16


esphome:
  name: ${name}
  comment: ${device_description}
  min_version: 2024.6.0
  project:
    name: "syssi.esphome-seplos-bms"
    version: 1.2.0

esp32:
  board: esp32dev
  framework:
    type: arduino


external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: xxxxx
  password: yyyyy


logger:
  level: DEBUG

# If you use Home Assistant please remove this `mqtt` section and uncomment the `api` component!
# The native API has many advantages over MQTT: https://esphome.io/components/api.html#advantages-over-mqtt

# api:
api:
  encryption:
    key: "ojzFSPil8HycGVTIQ3oH3cDmkM8RztfQE1ldhthgL8o="  

  
ota:
  - platform: esphome
    password: "1e13cbf036a5fab0a8608dece9fc9f84"

uart:
  id: uart_0
  # Please set the default baudrate of your Seplos BMS model here. It's sometimes 19200 baud instead of 9600.
  baud_rate: 19200
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}
  # The increased RX buffer size is important because
  # the full BMS response must fit into the buffer
  rx_buffer_size: 384

seplos_modbus:
  id: modbus0
  uart_id: uart_0
  rx_timeout: 150ms

seplos_bms:
  id: bms0
  # Dip switch configuration of a single pack setup / address 0x0
  #  8    7    6    5    4    3    2    1
  # off, off, off, off, off, off, off, off
  address: 0x00
  # Known protocol versions: 0x20 (Seplos), 0x26 (Boqiang)
  protocol_version: 0x20
  seplos_modbus_id: modbus0
  update_interval: 10s

sensor:
  - platform: seplos_bms
    min_cell_voltage:
      name: "${name} min cell voltage"
    max_cell_voltage:
      name: "${name} max cell voltage"
    min_voltage_cell:
      name: "${name} min voltage cell"
    max_voltage_cell:
      name: "${name} max voltage cell"
    delta_cell_voltage:
      name: "${name} delta cell voltage"
    average_cell_voltage:
      name: "${name} average cell voltage"
    cell_voltage_1:
      name: "${name} cell voltage 1"
    cell_voltage_2:
      name: "${name} cell voltage 2"
    cell_voltage_3:
      name: "${name} cell voltage 3"
    cell_voltage_4:
      name: "${name} cell voltage 4"
    cell_voltage_5:
      name: "${name} cell voltage 5"
    cell_voltage_6:
      name: "${name} cell voltage 6"
    cell_voltage_7:
      name: "${name} cell voltage 7"
    cell_voltage_8:
      name: "${name} cell voltage 8"
    cell_voltage_9:
      name: "${name} cell voltage 9"
    cell_voltage_10:
      name: "${name} cell voltage 10"
    cell_voltage_11:
      name: "${name} cell voltage 11"
    cell_voltage_12:
      name: "${name} cell voltage 12"
    cell_voltage_13:
      name: "${name} cell voltage 13"
    cell_voltage_14:
      name: "${name} cell voltage 14"
    cell_voltage_15:
      name: "${name} cell voltage 15"
    cell_voltage_16:
      name: "${name} cell voltage 16"
    temperature_1:
      name: "${name} temperature 1"
    temperature_2:
      name: "${name} temperature 2"
    temperature_3:
      name: "${name} temperature 3"
    temperature_4:
      name: "${name} temperature 4"
    temperature_5:
      name: "${name} environment temperature"
    temperature_6:
      name: "${name} mosfet temperature"
    total_voltage:
      name: "${name} total voltage"
    current:
      name: "${name} current"
    power:
      name: "${name} power"
    charging_power:
      name: "${name} charging power"
    discharging_power:
      name: "${name} discharging power"
    residual_capacity:
      name: "${name} residual capacity"
    battery_capacity:
      name: "${name} battery capacity"
    rated_capacity:
      name: "${name} rated capacity"
    state_of_charge:
      name: "${name} state of charge"
    charging_cycles:
      name: "${name} charging cycles"
    state_of_health:
      name: "${name} state of health"
    port_voltage:
      name: "${name} port voltage"
```
