### DISCUSSION TITLE
How to Update

### DISCUSSION THREAD

**Discussion by Mark-HomeAssistantTC** [syssi/esphome-seplos-bms#133] [Q&A] [answered]
Hi there,
I used the V 1.1.0 for a while without problems.
now I realised that there is a V 1.2.0.

Is there an easy way to update?

I thought through the "refresh" the repository automaticly.

Kind regards

**Comment by syssi** [comment]
Per default you are using this external component source:

```
substitutions:
  external_components_source: github://syssi/esphome-seplos-bms@main
```

this means you are pulling always the most recent development version (from the `main` branch). If you want to stick to a selected version you can use one of the release tags here:

```
substitutions:
  external_components_source: github://syssi/esphome-seplos-bms@1.2.0
```

This section

```
esphome:
  name: ${name}
  comment: ${device_description}
  min_version: 2024.6.0
  project:
    name: "syssi.esphome-seplos-bms"
    version: 1.2.0
```

is part of your local YAML configuration and gets out of sync over time. It just indicates which YAML configuration (version) did you use as template in the past. F.e. if new sensors gets added/implemented you have to update the YAML configuration manually.
