### DISCUSSION TITLE
MQTT posible

### DISCUSSION THREAD

**Discussion by manznOnly** [syssi/esphome-seplos-bms#50] [General]
Hy Syssi,

thank you for your great work - is it possible to combine the MQTT stack from esphome with your sensor?
Found a nice MQTT integration for victron - so I could feed the cerbo and home assistant with the same data.

br,
manzn

**Comment by syssi** [comment]
If you remove the `api:` and add these lines to the YAML

```
mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  id: mqtt_client
```

all sensors will be published using MQTT.
