### DISCUSSION TITLE
use Batter Monitor + Virtual Com port to access bms via esp32

### DISCUSSION THREAD

**Discussion by Pho3niX90** [syssi/esphome-seplos-bms#76] [Ideas]
Has anyone succeeded yet with creating a virtual com port using software such as NBVirtualCommPort, and connecting remotely to the bms? Could this even be implemented into the current solution?

**Comment by syssi** [comment]
You are looking for a solution to forward serial traffic over the network. Please try this external component instead:

https://github.com/oxan/esphome-stream-server

I've used the component here to make the serial line of a zigbee radio accessible via network:

https://github.com/syssi/esphome-zb-gw03/blob/main/packages/core.yaml

**Reply by Pho3niX90** [reply]
Thank you, i am completely new to the esphome thing. Would this just be a matter of adding the component to the esp32-example? Would the 3 firmwares run in parallel? Or is an additional esp32 required?

**Reply by syssi** [reply]
ESPHome is a code-generator / firmware generator. You have to describe your firmware / required features using building blocks via the YAML configuration. 

This is a basic YAML configuration which wires the `uart` component to the `stream_server`:

```
substitutions:
  name: stream-server
  tx_pin: GPIO16
  rx_pin: GPIO17

esphome:
  name: ${name}

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf

external_components:
  - source: github://oxan/esphome-stream-server
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:

logger:
  level: DEBUG

api:
  reboot_timeout: 0s

uart:
  - id: uart_0
    baud_rate: 115200
    tx_pin: ${tx_pin}
    rx_pin: ${rx_pin}

stream_server:
  - uart_id: uart_0
    port: 6638
```

You have to attach the UART pins of the BMS to `GPIO16/GPIO17` here. The serial data / communication will be available using TCP port 6638. You can load multiple `uart` components (if you use a ESP32 up to 3 hardware UARTs are supported).
