### DISCUSSION TITLE
Dynamic update interval

### DISCUSSION THREAD

**Discussion by innerlurken** [syssi/esphome-seplos-bms#77] [Q&A] [answered]
Hi, thanks for this, its great, has made controlling my solar system so much easier & better. I have a quick question, would it be possible to make the update_interval dynamic? or allow the value to be templatable? my reason is i have a separate charging system for when my solar panels out do the inverters 3kw battery charge limit, but want it to be able to respond very fast, but obviously don't want to be polling the bms that fast normally.

Thanks for any suggestion in advance

**Comment by syssi** [comment, marked as answer]
It's a bit hacky but possible. Take a look at this thread: https://community.home-assistant.io/t/dynamically-change-update-interval/108074/9

**Reply by innerlurken** [reply]
Thanks, that is great 

This is what I did to get it working for me

```
seplos_bms:
  - id: battery_bank0
    address: 0x00
    seplos_modbus_id: modbus0
    update_interval: never
  - id: battery_bank1
    address: 0x01
    seplos_modbus_id: modbus0
    update_interval: never

interval:
  - id: dynamic_update_interval_fast
    interval: 0.5s
    then:
      - if:
          condition:
            - lambda: |-
                return id(homeassistant_time).now().hour < 7;
          then:
            - component.update: battery_bank0
            - delay: 150ms
            - component.update: battery_bank1

  - id: dynamic_update_interval_slow
    interval: 5s
    then:
      - if:
          condition:
            - lambda: |-
                return id(homeassistant_time).now().hour >= 7;
          then:
            - component.update: battery_bank0
            - delay: 150ms
            - component.update: battery_bank1
```
