### ISSUE TITLE
Add multiple batteries example

### ISSUE THREAD

**Issue by syssi** [syssi/esphome-seplos-bms#11]
```
uart:
  id: uart0
  baud_rate: 9600
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}
  rx_buffer_size: 384

seplos_modbus:
  id: modbus0
  uart_id: uart0

seplos_bms:
  - id: bms0
    seplos_modbus_id: modbus0
    address: 0x01
  - id: bms1
    seplos_modbus_id: modbus0
    address: 0x02

sensor:
  - platform: seplos_bms
    seplos_bms_id: bms0
    total_voltage:
      name: "${name} total voltage"
    state_of_charge:
      name: "${name} state of charge"

  - platform: seplos_bms
    seplos_bms_id: bms1
    total_voltage:
      name: "${name} total voltage"
    state_of_charge:
      name: "${name} state of charge"
```

Requires: https://github.com/syssi/esphome-seplos-bms/issues/7
