### ISSUE TITLE
3 Seplos V2 on one ESP32

### ISSUE THREAD

**Issue by rira2005** [syssi/esphome-seplos-bms#122]
Hi,

I currently have three Seplos 2.0 BMS, each connected to its own ESP32 (so three ESP32s in total).
This feels like an overhead to me. My idea is to use a single ESP32 for all three UART connections.

But how should the ESPHome configuration look like? Does anyone have an idea?
Thanks!

substitutions:
  name: seplos-bms1-2-3
  friendly_name: Seplos BMS1-2-3
  device_description: "Monitor a Seplos BMS via RS485"
  external_components_source: github://syssi/esphome-seplos-bms@main
  tx_pin_bms1: GPIO4
  rx_pin_bms1: GPIO5
  tx_pin_bms2: GPIO16
  rx_pin_bms2: GPIO17
  tx_pin_bms3: GPIO22
  rx_pin_bms3: GPIO23
  id1: bms1

esphome:
  name: "seplos-bms1-2-3"
  friendly_name: Seplos BMS1-2-3

external_components:
  - source: ${external_components_source}
    refresh: 0s

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  id: Seplos_BMS1_2_3

captive_portal:

uart:
  id: uart_0
  # Please set the default baudrate of your Seplos BMS model here. It's sometimes 19200 baud instead of 9600.
  baud_rate: 19200
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}
  # The increased RX buffer size is important because
  # the full BMS response must fit into the buffer
  rx_buffer_size: 384
  debug:
    dummy_receiver: false
    direction: BOTH
    # after:
    #   delimiter: "\r"
    # sequence:
    #   - lambda: UARTDebug::log_string(direction, bytes);

seplos_modbus:
  id: modbus0
  uart_id: uart_0
  rx_timeout: 150ms

seplos_bms:
  id: bms1
  # Dip switch configuration of a single pack setup / address 0x0
  #  8    7    6    5    4    3    2    1
  # off, off, off, off, off, off, off, off
  address: 0x01
  # Known protocol versions: 0x20 (Seplos), 0x26 (Boqiang)
  protocol_version: 0x20
  seplos_modbus_id: modbus0
  update_interval: 60s

sensor:
  - platform: seplos_bms
    min_cell_voltage:
      name: "${name} min cell voltage"
    max_cell_voltage:
      name: "${name} max cell voltage"
    min_voltage_cell:
      name: "${name} min voltage cell"
    max_voltage_cell:
      name: "${name} max voltage cell"
    delta_cell_voltage:
      name: "${name} delta cell voltage"
    average_cell_voltage:
      name: "${name} average cell voltage"
    cell_voltage_1:
      name: "${name} cell voltage 1"
    cell_voltage_2:
      name: "${name} cell voltage 2"
    cell_voltage_3:
      name: "${name} cell voltage 3"
    cell_voltage_4:
      name: "${name} cell voltage 4"
    cell_voltage_5:
      name: "${name} cell voltage 5"
    cell_voltage_6:
      name: "${name} cell voltage 6"
    cell_voltage_7:
      name: "${name} cell voltage 7"
    cell_voltage_8:
      name: "${name} cell voltage 8"
    cell_voltage_9:
      name: "${name} cell voltage 9"
    cell_voltage_10:
      name: "${name} cell voltage 10"
    cell_voltage_11:
      name: "${name} cell voltage 11"
    cell_voltage_12:
      name: "${name} cell voltage 12"
    cell_voltage_13:
      name: "${name} cell voltage 13"
    cell_voltage_14:
      name: "${name} cell voltage 14"
    cell_voltage_15:
      name: "${name} cell voltage 15"
    cell_voltage_16:
      name: "${name} cell voltage 16"
    temperature_1:
      name: "${name} temperature 1"
    temperature_2:
      name: "${name} temperature 2"
    temperature_3:
      name: "${name} temperature 3"
    temperature_4:
      name: "${name} temperature 4"
    temperature_5:
      name: "${name} environment temperature"
    temperature_6:
      name: "${name} mosfet temperature"
    total_voltage:
      name: "${name} total voltage"
    current:
      name: "${name} current"
    power:
      name: "${name} power"
    charging_power:
      name: "${name} charging power"
    discharging_power:
      name: "${name} discharging power"
    residual_capacity:
      name: "${name} residual capacity"
    battery_capacity:
      name: "${name} battery capacity"
    rated_capacity:
      name: "${name} rated capacity"
    state_of_charge:
      name: "${name} state of charge"
    charging_cycles:
      name: "${name} charging cycles"
    state_of_health:
      name: "${name} state of health"
    port_voltage:
      name: "${name} port voltage"
  - platform: uptime
    type: seconds
    name: Uptime Sensor       

switch:
  - platform: restart
    name: "Restart ESP"

  - platform: safe_mode
    name: "Restart ESP (Safe Mode)"

**Comment by syssi** [comment]
You configuration must look like this:

```
substitutions:
  name: seplos-bms1-2-3
  friendly_name: Seplos BMS1-2-3
  device_description: "Monitor a Seplos BMS via RS485"
  external_components_source: github://syssi/esphome-seplos-bms@main
  tx_pin_bms1: GPIO4
  rx_pin_bms1: GPIO5
  tx_pin_bms2: GPIO16
  rx_pin_bms2: GPIO17
  tx_pin_bms3: GPIO22
  rx_pin_bms3: GPIO23

esphome:
  name: "seplos-bms1-2-3"
  friendly_name: Seplos BMS1-2-3

external_components:
  - source: ${external_components_source}
    refresh: 0s

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:
  encryption:

ota:
  platform: esphome


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  id: Seplos_BMS1_2_3

captive_portal:

uart:
  - id: uart_bms0
    baud_rate: 19200
    tx_pin: ${tx_pin_bms0}
    rx_pin: ${rx_pin_bms0}
    rx_buffer_size: 384
  - id: uart_bms1
    baud_rate: 19200
    tx_pin: ${tx_pin_bms1}
    rx_pin: ${rx_pin_bms1}
    rx_buffer_size: 384
  - id: uart_bms2
    baud_rate: 19200
    tx_pin: ${tx_pin_bms2}
    rx_pin: ${rx_pin_bms2}
    rx_buffer_size: 384
    
seplos_modbus:
  - id: modbus_bms0
    uart_id: uart_bms0
    rx_timeout: 150ms
  - id: modbus_bms1
    uart_id: uart_bms1
    rx_timeout: 150ms
  - id: modbus_bms2
    uart_id: uart_bms2
    rx_timeout: 150ms

seplos_bms:
  - id: bms0
    seplos_modbus_id: modbus_bms0
    address: 0x01
    protocol_version: 0x20
    update_interval: 60s
  - id: bms1
    seplos_modbus_id: uart_bms1
    address: 0x01
    protocol_version: 0x20
    update_interval: 60s
  - id: bms2
    seplos_modbus_id: uart_bms2
    address: 0x01
    protocol_version: 0x20
    update_interval: 60s

sensor:
  - platform: seplos_bms
    seplos_bms_id: bms0
    total_voltage:
      name: "bsm0 total voltage"
  - platform: seplos_bms
    seplos_bms_id: bms1
    total_voltage:
      name: "bms1 total voltage"
  - platform: seplos_bms
    seplos_bms_id: bms1
    total_voltage:
      name: "bms1 total voltage"
# ...
```

**Comment by rira2005** [comment]
Jep i tried this allready but get an error back...


INFO ESPHome 2024.12.4
INFO Reading configuration /config/esphome/seplos-bms1-2-3.yaml...
INFO Updating https://github.com/syssi/esphome-seplos-bms.git@main
WARNING GPIO5 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
Failed config

seplos_bms: [source /config/esphome/seplos-bms1-2-3.yaml:78]
  - id: bms0
    seplos_modbus_id: modbus_bms0
    address: 0x01
    protocol_version: 0x20
    update_interval: 60s
    override_cell_count: 0
  - id: bms1
    
    ID 'uart_bms1' of type uart::ESP32ArduinoUARTComponent doesn't inherit from seplos_modbus::SeplosModbus. Please double check your ID is pointing to the correct value.
    seplos_modbus_id: uart_bms1
    address: 0x01
    protocol_version: 0x20
    update_interval: 60s
    override_cell_count: 0
  - id: bms2
    
    ID 'uart_bms2' of type uart::ESP32ArduinoUARTComponent doesn't inherit from seplos_modbus::SeplosModbus. Please double check your ID is pointing to the correct value.
    seplos_modbus_id: uart_bms2
    address: 0x01
    protocol_version: 0x20


substitutions:
  name: seplos-bms1-2-3
  friendly_name: Seplos BMS1-2-3
  device_description: "Monitor a Seplos BMS via RS485"
  external_components_source: github://syssi/esphome-seplos-bms@main
  tx_pin_bms0: GPIO4
  rx_pin_bms0: GPIO5
  tx_pin_bms1: GPIO16
  rx_pin_bms1: GPIO17
  tx_pin_bms2: GPIO22
  rx_pin_bms2: GPIO23

esphome:
  name: "seplos-bms1-2-3"
  friendly_name: Seplos BMS1-2-3

external_components:
  - source: ${external_components_source}
    refresh: 0s

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

# Enable Home Assistant API
api:
  encryption:


ota:
  - platform: esphome


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  id: Seplos_BMS1_2_3

uart:
  - id: uart_bms0
    baud_rate: 19200
    tx_pin: ${tx_pin_bms0}
    rx_pin: ${rx_pin_bms0}
    rx_buffer_size: 384
  - id: uart_bms1
    baud_rate: 19200
    tx_pin: ${tx_pin_bms1}
    rx_pin: ${rx_pin_bms1}
    rx_buffer_size: 384
  - id: uart_bms2
    baud_rate: 19200
    tx_pin: ${tx_pin_bms2}
    rx_pin: ${rx_pin_bms2}
    rx_buffer_size: 384
    
seplos_modbus:
  - id: modbus_bms0
    uart_id: uart_bms0
    rx_timeout: 150ms
  - id: modbus_bms1
    uart_id: uart_bms1
    rx_timeout: 150ms
  - id: modbus_bms2
    uart_id: uart_bms2
    rx_timeout: 150ms

seplos_bms:
  - id: bms0
    seplos_modbus_id: modbus_bms0
    address: 0x01
    protocol_version: 0x20
    update_interval: 60s
  - id: bms1
    seplos_modbus_id: uart_bms1
    address: 0x01
    protocol_version: 0x20
    update_interval: 60s
  - id: bms2
    seplos_modbus_id: uart_bms2
    address: 0x01
    protocol_version: 0x20
    update_interval: 60s

sensor:
  - platform: seplos_bms
    seplos_bms_id: bms0
    total_voltage:
      name: "bsm0 total voltage"
  - platform: seplos_bms
    seplos_bms_id: bms1
    total_voltage:
      name: "bms1 total voltage"
  - platform: seplos_bms
    seplos_bms_id: bms2
    total_voltage:
      name: "bms1 total voltage"


  - platform: uptime
    type: seconds
    name: Uptime Sensor       

switch:
  - platform: restart
    name: "Restart ESP"

  - platform: safe_mode
    name: "Restart ESP (Safe Mode)"

**Comment by syssi** [comment]
My fault. This is the fixed / a valid version:

```
substitutions:
  name: seplos-bms1-2-3
  friendly_name: Seplos BMS1-2-3
  device_description: "Monitor a Seplos BMS via RS485"
  external_components_source: github://syssi/esphome-seplos-bms@main
  tx_pin_bms0: GPIO4
  rx_pin_bms0: GPIO5
  tx_pin_bms1: GPIO16
  rx_pin_bms1: GPIO17
  tx_pin_bms2: GPIO22
  rx_pin_bms2: GPIO23

esphome:
  name: "seplos-bms1-2-3"
  friendly_name: Seplos BMS1-2-3

external_components:
  - source: ${external_components_source}
    refresh: 0s

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:

ota:
  platform: esphome


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  id: Seplos_BMS1_2_3

captive_portal:

uart:
  - id: uart_bms0
    baud_rate: 19200
    tx_pin: ${tx_pin_bms0}
    rx_pin: ${rx_pin_bms0}
    rx_buffer_size: 384
  - id: uart_bms1
    baud_rate: 19200
    tx_pin: ${tx_pin_bms1}
    rx_pin: ${rx_pin_bms1}
    rx_buffer_size: 384
  - id: uart_bms2
    baud_rate: 19200
    tx_pin: ${tx_pin_bms2}
    rx_pin: ${rx_pin_bms2}
    rx_buffer_size: 384

seplos_modbus:
  - id: modbus_bms0
    uart_id: uart_bms0
    rx_timeout: 150ms
  - id: modbus_bms1
    uart_id: uart_bms1
    rx_timeout: 150ms
  - id: modbus_bms2
    uart_id: uart_bms2
    rx_timeout: 150ms

seplos_bms:
  - id: bms0
    seplos_modbus_id: modbus_bms0
    address: 0x01
    protocol_version: 0x20
    update_interval: 60s
  - id: bms1
    seplos_modbus_id: modbus_bms1
    address: 0x01
    protocol_version: 0x20
    update_interval: 60s
  - id: bms2
    seplos_modbus_id: modbus_bms2
    address: 0x01
    protocol_version: 0x20
    update_interval: 60s

sensor:
  - platform: seplos_bms
    seplos_bms_id: bms0
    total_voltage:
      name: "bsm0 total voltage"
  - platform: seplos_bms
    seplos_bms_id: bms1
    total_voltage:
      name: "bms1 total voltage"
  - platform: seplos_bms
    seplos_bms_id: bms1
    total_voltage:
      name: "bms1 total voltage"
```
